services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password 
    depends_on:
      - database
    networks:
      - client-server

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/client/src
    environment:
      BACKEND_PROXY_URL: http://server:8080 
    depends_on:
      - server
    networks:
      - client-server
      - server-database

  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - server-database

networks:
  client-server:
    driver: bridge
  server-database:
    driver: bridge

